travis:
  secure:
    BINSTAR_TOKEN: CYlo+Zn5krRJe9391QlNud4KHElQ6fcgzcNq1wQXtVm9BxT0ibsoAfGTpbdEU/+RWTeFE83IAStJFuZka5F/8VPWSYyrmD0XN4HAd5H5X3xX4XY7jvA/kAcqrZ56BXbiiSybVVT3LfLVDihQA1qIHgagfvWfLqu0TVLEZ4bWfw1v2kGT/d/brrW5cCKKiwbBktq0+Ccm0Uce499FakzGctW8X628+tZQfsxfh1LTrKjcpBw/AZBk5tjGy3jXXRzFMizYq+d0lLZySTTyCUlROFTn8HanWTtn2mGr89Hzp3knQGhJn38f4VGrnK4DFAMfNlabsVNOfsmWRNzEboa7tpfdgOjY9Ko1DjMSpbksrEJx0Hi4bzxNJaaXQaqAgiMoNBeIEMY5j4AvIQDRyOZbN7Lv7luPDyZl54a/4VfOqJF9IW6oFCPo+WtakXoshafqudB5DOFR66loHCcE541XF61u0ensUP3oxs3ns58sIzfknxAd5MSer0Mt28PFT/LrCjjMTWqNKktzMKHJ22OSqrXiseNWaFHv4Z8SySZbi8GRIYe3XmVsbxb/PfU1RapjZHjjZVnQ5BrbeGV03j7pf+2xEZvOrh3LqqPDs5CvV/pBGClQin/zfW/69k7AiCS4W9cJJkL7+zNRaOBCdJwg9eKg2TqoA4FS0+S+2E3NJtI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
